// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiyDh8-lCkThmlq8kEbMsI6Q0iPZtE-h4',
    appId: '1:890343137687:web:b502d58dba04c4212664d2',
    messagingSenderId: '890343137687',
    projectId: 'aegistrack-4d8af',
    authDomain: 'aegistrack-4d8af.firebaseapp.com',
    storageBucket: 'aegistrack-4d8af.firebasestorage.app',
    measurementId: 'G-6F20L8J5GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjjYyiffib2cUuiN9U-foVZYx4jkucby4',
    appId: '1:890343137687:android:bcdda45ca6e4cbf52664d2',
    messagingSenderId: '890343137687',
    projectId: 'aegistrack-4d8af',
    storageBucket: 'aegistrack-4d8af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDqfoFGkvNjEklvl-GIcqW47-p9_9r6o',
    appId: '1:890343137687:ios:a9a8d50300bf019f2664d2',
    messagingSenderId: '890343137687',
    projectId: 'aegistrack-4d8af',
    storageBucket: 'aegistrack-4d8af.firebasestorage.app',
    iosBundleId: 'app.base44.aegisTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZDqfoFGkvNjEklvl-GIcqW47-p9_9r6o',
    appId: '1:890343137687:ios:a9a8d50300bf019f2664d2',
    messagingSenderId: '890343137687',
    projectId: 'aegistrack-4d8af',
    storageBucket: 'aegistrack-4d8af.firebasestorage.app',
    iosBundleId: 'app.base44.aegisTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiyDh8-lCkThmlq8kEbMsI6Q0iPZtE-h4',
    appId: '1:890343137687:web:07aa7f15450226c42664d2',
    messagingSenderId: '890343137687',
    projectId: 'aegistrack-4d8af',
    authDomain: 'aegistrack-4d8af.firebaseapp.com',
    storageBucket: 'aegistrack-4d8af.firebasestorage.app',
    measurementId: 'G-6BGGHT7YX0',
  );

}